CREATE TABLE IF NOT EXISTS dcl_currency (
  cur_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cur_name VARCHAR(10) NOT NULL,
  cur_no_round SMALLINT,
  cur_sort_order SMALLINT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_dcl_currency_name ON dcl_currency(cur_name);
