CREATE TABLE IF NOT EXISTS dcl_contractor (
  ctr_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ctr_name VARCHAR(200) NOT NULL,
  ctr_email VARCHAR(40),
  ctr_bank_props VARCHAR(800),
  ctr_unp VARCHAR(15),
  ctr_full_name VARCHAR(300),
  ctr_block SMALLINT,
  rpt_id INTEGER NOT NULL DEFAULT 1,
  cut_id INTEGER NOT NULL DEFAULT 1,
  ctr_phone VARCHAR(100),
  ctr_fax VARCHAR(100),
  ctr_index VARCHAR(20),
  ctr_region VARCHAR(50),
  ctr_place VARCHAR(50),
  ctr_street VARCHAR(50),
  ctr_building VARCHAR(10),
  ctr_add_info VARCHAR(1000)
);

CREATE INDEX IF NOT EXISTS idx_dcl_contractor_name ON dcl_contractor(ctr_name);
