CREATE TABLE IF NOT EXISTS dcl_account (
  acc_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ctr_id INTEGER NOT NULL,
  acc_name VARCHAR(100),
  acc_account VARCHAR(35),
  cur_id INTEGER,
  acc_index SMALLINT
);

CREATE TABLE IF NOT EXISTS dcl_contact_person (
  cps_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ctr_id INTEGER NOT NULL,
  cps_name VARCHAR(200) NOT NULL,
  cps_phone VARCHAR(150),
  cps_fax VARCHAR(150),
  cps_block SMALLINT,
  cps_position VARCHAR(150),
  cps_on_reason VARCHAR(150),
  cps_email VARCHAR(50),
  cps_mob_phone VARCHAR(150),
  cps_contract_comment VARCHAR(300),
  cps_fire SMALLINT
);

CREATE TABLE IF NOT EXISTS dcl_contractor_user (
  ctr_id INTEGER NOT NULL,
  usr_id INTEGER NOT NULL,
  PRIMARY KEY (ctr_id, usr_id)
);
